### ISSUE TITLE
Test server, reproduce connection reset

### ISSUE THREAD

**Issue by boborjan** [epam/Wilma#2]
Wilma Test Server should be able to cause the following exception in Wilma:

08:53:16.652 [SocketListener0-59] INFO  n.l.b.p.http.BrowserMobHttpClient - java.net.SocketException: Connection reset when requesting http://testserver/connectionreset

As a bonus, it would be good if Wilma would answer back with the cause of the exception.
(For example: java.net.SocketException: Connection reset when requesting http://testserver/connectionreset)

**Comment by tkohegyi** [comment]
Some notes (http://stackoverflow.com/questions/585599/whats-causing-my-java-net-socketexception-connection-reset): 
The Exception means that the socket was closed unexpectedly from the other side. Since you are calling a web service, this should not happen - most likely you're sending a request that triggers a bug in the web service.

Try logging the entire request in those cases, and see if you notice anything unusual.
