### ISSUE TITLE
ActiveMQ JmsTemplate Gotchas

### ISSUE THREAD

**Issue by boborjan** [epam/Wilma#30]
From http://activemq.apache.org/jmstemplate-gotchas.html
 - Never use a regular ConnectionFactory unless you are totally sure it does all the pooling you need.
 - If you are only publishing messages and you are not in an EJB container and you are using ActiveMQ, then you can use either the PooledConnectionFactory or the Spring CachingConnectionFactory

It seems like that both jmsTemplateForIndexing in indexing-application-context.xml and jmsTemplate in logger-application-context.xml go against this advice.

**Comment by tkohegyi** [comment]
It is unclear how old the referred article is.
Since we use ActiveMQ 5.11.1, the speed of the queues are awesome. I.e. much-much better than their reliability and speed was in 4.x and in 5.7 versions.

It works perfectly now, so don't think that we should change it. But thanks for the notification, if any problem occurs with the actual ActiveMQ setup in Wilma, we must remember.

**Comment by tkohegyi** [comment]
closing now, as no problem detected at message queues
